#SPDX-License-Identifier: MIT-0
---
# defaults file for zabbix-agent
# zabbix_version: "7.0"
zabbix_repos:
  Ubuntu: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu{{ ansible_facts['distribution_major_version'] }}.04_all.deb"
  Rocky: https://repo.zabbix.com/zabbix/7.0/rocky/{{ ansible_facts["distribution_major_version"] }}/x86_64/zabbix-release-latest-7.0.el{{ ansible_facts["distribution_major_version"] }}.noarch.rpm
  Debian: https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.0+debian{{ ansible_facts["distribution_major_version"] }}_all.deb



zabbix_server: "192.168.85.140"
zabbix_server_active: "192.168.85.140"
zabbix_hostname: "{{ inventory_hostname }}"
zabbix_hostmetadata: "autoregistration"
local_config_file_name: "/etc/zabbix/zabbix_agent2.d/local.conf"
