- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags: set_hostname

- name: doing something - sleep
  shell: |
    sleep 6
  tags: sleep
  delegate_to: loadbalancer


- name: show ansible_hostname and ip addresses
  debug:
    msg: "the host: {{ inventory_hostname }} has the ip address : {{ ansible_host }}"
  tags: show_ip_addr


- name: show vars
  debug:
    msg: "{{ var1.family.bro }}"
  tags: show vars

- name: show vars
  debug:
    msg: "{{ dns_servers2 }}"
  tags: show vars


- name: Show interface config
  debug:
    msg: "Interface {{ interface.name }} has IP {{ interface.ip }}"


- name: Configure interfaces
  debug:
    msg: "Configuring {{ item.name }} with IP {{ item.ip }}"
  loop: "{{ interfaces }}"
